name: internshala_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: 'assets/pngs/IS_logo.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/


